tutorial/blog/urls.py
from django.conf.urls import url
from django.urls import path

from blog.views.views import PostListView, PostDetailView, SearchResultView, SearchPageView
from blog.views.examplereflex import ExamplereflexView
from blog.views.examplereflex_with_js import ExamplereflexWithJsView
from blog.views.book_search import BookSearch
from blog.views.chat import ChatView
from blog.views.signup import SignupView
from blog.views.blog_search import BlogSearchView
from blog.views.progress_bar import ProgressBarView

from blog.models import Post


app_name = 'blog'


urlpatterns = [
    url(r'^$', PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(), name='post_detail'),
    path('search/', SearchResultView.as_view(), name='search_result'),
    path('search-page/', SearchPageView.as_view(), name='search_page'),
    path('example-reflex/', ExamplereflexView.as_view(), name='example_reflex'),
    path('example-reflex-js/', ExamplereflexWithJsView.as_view(), name='example_reflex_js'),
    path('book-search-reflex/', BookSearch.as_view(), name='book_search_reflex'),
    path('chat-reflex/', ChatView.as_view(), name='chat_reflex'),
    path('signup-reflex/', SignupView.as_view(), name='signup_reflex'),
    path('blog-search-reflex/', BlogSearchView.as_view(), name='blog_search_reflex'),
    path('progress-bar-reflex/', ProgressBarView.as_view(), name='progress_bar_reflex'),
]

tutorial/chat/urls.py
from django.urls import path

from .views import ChatView, RoomView

app_name = 'chat'

urlpatterns = [
    path('', ChatView.as_view(), name='chat'),
    path('<str:room_name>/', RoomView.as_view(), name='room'),
]

tutorial/tutorial/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView


urlpatterns = [
    path(r'comments/', include('django_comments_xtd.urls')),
    path(r'admin/', admin.site.urls),
    path(r'blog/', include('blog.urls', namespace='blog')),
    path(r'chat/', include('chat.urls', namespace='chat')),
    path(r'', TemplateView.as_view(template_name="home.html"), name='homepage'),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

tutorial/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class PublicManager(models.Manager):
    def get_queryset(self):
        return super(PublicManager, self).get_queryset()\
                                         .filter(publish__lte=timezone.now())


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    allow_comments = models.BooleanField('allow comments', default=True)
    publish = models.DateTimeField(default=timezone.now)
    objects = PublicManager()  # Our custom manager.

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       kwargs={'year': self.publish.year,
                               'month': self.publish.strftime('%b'),
                               'day': self.publish.strftime('%d'),
                               'slug': self.slug})


class Subscription(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=256)

tutorial/chat/models.py
from django.db import models

# Create your models here.

tutorial/blog/views/blog_search.py
from django.views.generic.base import TemplateView


class BlogSearchView(TemplateView):
    template_name = 'blog/blog_search.html'
    subtitle = None

tutorial/blog/views/book_search.py
from django.views.generic.base import TemplateView
from .mixins import BookSearchMixin


class BookSearch(BookSearchMixin, TemplateView):
    subtitle = 'Search Book'

tutorial/blog/views/chat.py
from django.views.generic.base import TemplateView
from django.core.cache import cache

class ChatView(TemplateView):
    subtitle = 'Chat'
    template_name = "blog/chat.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['chats'] = cache.get("chats", [])
        return context

tutorial/blog/views/examplereflex.py
from django.views.generic.base import TemplateView


class ExamplereflexView(TemplateView):
    template_name = 'blog/examplereflex.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['count'] = 0
        return context

tutorial/blog/views/examplereflex_with_js.py
from django.views.generic.base import TemplateView


class ExamplereflexWithJsView(TemplateView):
    template_name = 'blog/examplereflex_with_js.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['count'] = 0
        return context

tutorial/blog/views/mixins.py
from collections import defaultdict
from django.conf import settings
import os

BASE_PATH = settings.BASE_DIR


class BookSearchMixin():
    template_name = "blog/book_search_reflex.html"
    subtitle = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["some_data"] = 'placeholder_string'
        return context

tutorial/blog/views/progress_bar.py
from django.views.generic.base import TemplateView


class ProgressBarView(TemplateView):
    template_name = 'blog/progress_bar.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['status'] = 10
        return context

tutorial/blog/views/signup.py
from django.forms import ModelForm
from django.views.generic.edit import FormView

from blog.models import Subscription


class SubscriptionForm(ModelForm):
    class Meta:
        model = Subscription
        fields = ['name', 'email']


class SignupView(FormView):
    template_name = 'blog/signup.html'
    form_class = SubscriptionForm
    subtitle = 'Newsletter Signup'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['people'] = Subscription.objects.all()
        return context

tutorial/blog/views/views.py
from django.db.models import Q
import random
import time

from django.views.generic import ListView, DetailView, TemplateView

# use this import instead of short 'from .models' to escape RuntimeErros
# https://medium.com/@michal.bock/fix-weird-exceptions-when-running-django-tests-f58def71b59a
from blog.models import Post


class PostListView(ListView):
    model = Post
    context_object_name = "post_list"
    template_name = "blog/post_list.html"
    paginate_by=5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Added to see blue wait bar on top, as indication of working turbolinks
        time.sleep(random.randint(2, 3)) 
        return context


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Added to see blue wait bar on top, as indication of working turbolinks
        # time.sleep(random.randint(2, 4)) 
        return context


class SearchPageView(TemplateView):
    model = Post
    template_name = "blog/search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Added to see blue wait bar on top, as indication of working turbolinks
        # time.sleep(random.randint(2, 3)) 
        return context


class SearchResultView(ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'blog/search_results.html'
    paginate_by=5

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Post.objects.filter(
            Q(title__icontains=query) | Q(title__icontains=query)
        )

tutorial/chat/views.py
from django.views.generic import TemplateView


class ChatView(TemplateView):
    template_name = "chat/chat.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add somecontext here
        return context


class RoomView(TemplateView):
    template_name = "chat/room.html"

    room_name = None

    def get_object(self, queryset=None):
        return queryset.get(room_name=self.room_name)

tutorial/templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="turbolinks-root" content="/">
    <meta name="turbolinks-cache-control" content="no-cache">

    <title>{% block title %}django-comments-xtd tutorial{% endblock %}</title>
    <link 
      rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" 
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" 
      crossorigin="anonymous">

    <!-- Latest compiled and minified Bootstrap CSS -->
    <!-- link href="{% static 'css/bootstrap.lumen.min.css' %}" rel="stylesheet" -->
    <!-- link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" -->
    
    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores ALL css for project, and it was build with webpack CSS -->
    <link href="{% static 'app.css' %}" rel="stylesheet">
 
    <!-- Your stuff: Third-party javascript libraries go here -->
    <!-- script defer src="{% static 'js/bootstrap/jquery.min.js' %}"></script -->
    <!-- script defer src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script -->
    <!-- script defer src="{% static 'js/bootstrap/prism.js' %}"></script -->
    
    <!-- place app.js which is webpack build combination of all project .js files -->
    <script type="module" src="{% static 'app.js' %}" data-turbolinks-eval="false"></script>
    
  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarColor03">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'homepage' %}">Home
                <span class="visually-hidden">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:post_list' %}">Posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:search_page' %}">Search</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'chat:chat' %}">Channels</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reflexes</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'blog:example_reflex' %}">Count Reflex</a>
                <a class="dropdown-item" href="{% url 'blog:example_reflex_js' %}">Count Reflex Js</a>
                <a class="dropdown-item" href="{% url 'blog:book_search_reflex' %}">Book Search Reflex</a>
                <a class="dropdown-item" href="{% url 'blog:chat_reflex' %}">Chat Reflex</a>
                <a class="dropdown-item" href="{% url 'blog:signup_reflex' %}">Signup Reflex</a>
                <a class="dropdown-item" href="{% url 'blog:blog_search_reflex' %}">Posts Search Reflex</a>
                <a class="dropdown-item" href="{% url 'blog:progress_bar_reflex' %}">Progress Bar</a>
              </div>
            </li>
          </ul>
          <form class="d-flex" action="{% url 'blog:search_result' %}" method="get">
            <input name="q" class="form-control me-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row my-4">
        <div class="col-lg-12">
	      <h5 class="text-center">django-blog-example</h5>
          <hr/>
        </div>
      </div>
    </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <hr/>
          <p class="text-center text-muted small">django-blog-example.</p>
        </div>
      </div>
    </div>

    {% block extra-js %}
    {% endblock %}
  </body>
</html>

tutorial/templates/blog/blog_search.html
{% extends "base.html" %}
{% load static %}

{% load humanize %}

{% block subtitle %}{{ subtitle }}{% endblock subtitle %}

{% block content %}
<div class="container">
  <form data-controller="blog_search" data-reflex-root="#morph" class="">
    <input type="text" placeholder="search for a post ..." data-target="blog_search.query"
      data-action="debounced:input->blog_search#perform" class="form-control"/>
    <div id="morph">
      <div>
        <span data-target="blog_search.activity" class="" hidden>
          <i class="fas fa-spinner fa-spin"></i>
          Searching for posts...
        </span>
        <span data-target="blog_search.count" class="">
          <strong>{{count|default:0|intcomma}}</strong> posts found
        </span>
      </div>
      <table data-target="blog_search.list" {% if  not posts %} hidden {% endif %}>
        <thead>
          <tr>
            <th scope="col">Post</th>
            <th scope="col">Primary Key</th>
            <th scope="col">Date</th>
            <th scope="col">Author</th>
          </tr>
        </thead>
        <tbody>
          {% for post in posts|slice:'0:5'  %}
          <tr>
            <th scope="row"><h3><a class="nounderline" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3></th>
            <td>{{ post.pk }}</td>
            <td>{{ post.publish }}</td>
            <td>Anonymos</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </form>
</div>
{% endblock %}

tutorial/templates/blog/book_search_reflex.html
{% extends "base.html" %}
{% load static %}

{% load humanize %}

{% block subtitle %}{{ subtitle }}{% endblock subtitle %}

{% block content %}
<div>
  <form data-controller="book_search" data-reflex-root="#morph" >
    <input class="form-control me-sm-2" type="text" placeholder="search for a book ..." data-target="book_search.query"
      data-action="debounced:input->book_search#perform" />
    <div id="morph">
      <div>
  
        <span data-target="book_search.activity" class="" hidden>
          <i class="fas fa-spinner fa-spin"></i>
          Searching for books...
        </span>
        <span data-target="book_search.count" class="">
          <strong>{{count|default:0|intcomma}}</strong> books found
        </span>
      </div>
  
      <table data-target="book_search.list" {% if  not books %} hidden {% endif %}>
        <thead>
          <tr>
            <th scope="col">Subject</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Publish Date</th>
            <th scope="col">ISBN</th>
          </tr>
        </thead>
        <tbody>
          {% for book in books|slice:'0:5'  %}
          <tr>
            <td>{{book.subject|join:', '|truncatechars:10}} </td>
            <td>{{book.title|truncatechars:30}}</td>
            <td>{{book.author_name|join:', '|truncatechars:30}}</td>
            <td>{{book.publish_year.0 }}</td>
            <td>{{book.isbn.0|truncatechars:5}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </form>
</div>
{% endblock %}

tutorial/templates/blog/chat.html
{% extends "base.html" %}
{% load static %}

{% load humanize %}

{% block subtitle %}{{ subtitle }}{% endblock subtitle %}

{% block content %}
<article id="red"
    data-controller="chat"
    data-action="chats:added@document->chat#reload cable-ready:after-morph@document->chat#scroll"
    data-reflex-root="#chat-container"
    >
    <span id="chat-container" data-target="chat.list">
      {% for chat in chats  %}
        <aside class="message" style="min-height:auto; margin-top: 15px;">
          <p>
          {{ chat.message }} <sup>{{ chat.created_at|timesince }} ago </sup>
          </p>
        </aside>
      {% endfor %}
      <div>
        <h6>Messages stored <h3>{{chats|length}}</h3></h6>
        Note , that this Messages stored value is updated at every reflex action. It is inside data-reflex-root="#chat-container".
      </div>
    </span>
    <form>
      <textarea data-target="chat.input" placeholder="Type your message.." minlength="4"></textarea>
      <button data-action="click->chat#post" type="submit"> Send </button>
      <div>
        <h6>Messages stored <h3>{{chats|length}}</h3></h6>
        Note, that Messages stored value is not updated at every new message arrived,
         instead you have to reload the page.
          That is because it is not in data-reflex-root="#chat-container".
      </div>
    </form>
</article>
{% endblock %}

tutorial/templates/blog/examplereflex.html
{% extends 'base.html' %}


{% load static %}
{% block content %}
    
    <h3> This is simple reflex, it does not have javascript controller.</h3>

    <script src="{% static 'sockpuppet/sockpuppet.js' %}"></script>
    <a
      href="#"
      data-reflex="click->ExamplereflexReflex#increment"
      data-count="{{ count }}"
    >Increment </a><span>{{ count }}</span>
    
{% endblock content %}    

tutorial/templates/blog/examplereflex_with_js.html
{% extends 'base.html' %}


{% load static %}
{% block content %}
    
    
    
    <h3> This Reflex is compiled with webpack and it has javascript controller.</h3>
    <a  href="#"
        data-controller="examplereflex_with_js"
        data-action="click->examplereflex_with_js#increment"
        data-count="{{ count }}"
    >Increment </a><span>{{ count }}</span>
    
{% endblock content %}

tutorial/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load comments %}
{% load comments_xtd %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
<div class="pb-3">
  <h1 class="text-center">{{ object.title }}</h1>
  <p class="small text-center">{{ object.publish|date:"l, j F Y" }}</p>
</div>
<div>
  {{ object.body|linebreaks }}
</div>

{% get_comment_count for object as comment_count %}
<div class="pt-4 text-center">
  <a href="{% url 'blog:post_list' %}">Back to the post list</a>
  &nbsp;&sdot;&nbsp;
  {{ comment_count }} comment{{ comment_count|pluralize }}
  ha{{ comment_count|pluralize:"s,ve" }} been posted.
</div>

{% if object.allow_comments %}
<div class="card card-block mb-5">
  <div class="card-body">
    <h4 class="card-title text-center pb-3">Post your comment</h4>
      {% render_comment_form for object %}
  </div>
</div>
{% endif %}


{% if comment_count %}
<ul class="media-list">
  {% render_xtdcomment_tree for object allow_flagging allow_feedback show_feedback %}
</ul>
{% endif %}


{% block extra-js %}
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  crossorigin="anonymous"></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"></script>
<script>
  $(function() {
    $('[data-toggle="tooltip"]').tooltip({html: true});
  });
</script>
{% endblock extra-js %}



{% endblock content %}

tutorial/templates/blog/post_list.html
{% extends "base.html" %}
{% load comments %}


{% block content %}
<h1 class="pb-3 text-center">Blog</h1>

<div class="row justify-content-center flex-fill">
  <div class="col-md-10">
    {% for object in object_list %}
    <h3><a class="nounderline" href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
    <p class="date">Published {{ object.publish }}</p>
    {{ object.body|truncatewords:30|linebreaks }}


      {% get_comment_count for object as comment_count %}
      <p class="date">Published {{ object.publish }}
        {% if comment_count %}
            &sdot;&nbsp;{{ comment_count }} comment{{ comment_count|pluralize }}
        {% endif %}
      </p>


    {% endfor %}
  </div>
</div>

<ul class="mt-5 pagination justify-content-center">
  <li class="page-item{% if not page_obj.has_previous %} disabled{% endif %}">
    <a class="page-link" href="{{ url }}?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}">previous</a>
  </li>
  {% for page_number in page_range %}
  <li class="page-item{% if page_number == page_obj.number %} active{% endif %}">
    <a class="page-link" href="{{ url }}?page={{ page_number }}">{{ page_number }}</a>
  </li>
  {% endfor %}

  <li class="page-item{% if page_number == page_obj.number %} active{% endif %}">
    <a class="page-link" href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
  </li>

  <li class="page-item{% if not page_obj.has_next %} disabled{% endif %}">
    <a class="page-link" href="{{ url }}?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}">next</a>
  </li>
</ul>
{% endblock %}

tutorial/templates/blog/progress_bar.html
{% extends 'base.html' %}


{% load static %}
{% block content %}

    <h3> This is progress bar example. This is implemented with sockpuppet. This progress bar is updated every time user clicks a button.</h3>
    <h1>Progress Bar Demo</h1>

    <div class="progress">
      <div class="progress-bar progress-bar-striped progress-bar-animated"
           role="progressbar"
           aria-valuenow="75"
           aria-valuemin="0"
           aria-valuemax="100"
           style="width: {{ status }}%;"><b>{{ status }} %</b>
      </div>
    </div>

    <a  href="#"
        data-controller="progress_bar"
        data-action="click->progress_bar#increment"
        data-status="{{ status }}"
        class="btn btn-success"
    >Load</a>

    <h3>This progress bar is updated Automatically by server upon receiving client connection.</h3>
    <h1>Progress Bar with CableReady</h1>

    <div class="progress">
      <div id="progress-bar" class="progress-bar progress-bar-striped progress-bar-animated"
           role="progressbar"
           aria-valuenow="75"
           aria-valuemin="0"
           aria-valuemax="100"
           style="width: 10%;"><b>{{ status }} %</b>
      </div>
    </div>


{% endblock content %}

tutorial/templates/blog/search.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Search Page{% endblock title %}

{% block content %}
<h1>Search</h1>
<form class="form-inline mt-2 mt-md-0" action="{% url 'blog:search_result' %}" method="get">
  <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
</form>
{% endblock content %}

tutorial/templates/blog/search_results.html
{% extends 'base.html' %}

{% block title %}Search{% endblock title %}

{% block content %}
  <div class="jumbotron text-center" style="margin-bottom:0">
    <h1>Search</h1>
    <p>Click for details</p>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Post</th>
        <th scope="col">Primary Key</th>
        <th scope="col">Date</th>
        <th scope="col">Author</th>
      </tr>
    </thead>
    <tbody>
    {% for post in post_list %}
      <tr>
        <th scope="row"><h3><a class="nounderline" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3></th>
        <td>{{ post.pk }}</td>
        <td>{{ post.publish }}</td>
        <td>Anonymos</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock content %}

tutorial/templates/comments/400-debug.html
{% extends "base.html" %}

{% block title %}Bad request{% endblock %}

{% block content %}
<h3 class="text-center">Comment post not allowed</h3>
<p class="text-center">{{ why }}</p>
<hr/>
<p class="col-lg-offset-1 col-md-offset-1 text-muted">
  You're seeing this error because you have <code>DEBUG = True</code> in
  your Django settings file. Change that to <code>False</code>, and Django
  will display a standard 400 error page.
</p>
{% endblock %}

tutorial/templates/comments/form.html
{% load i18n %}
{% load comments %}

<form method="POST" action="{% comment_form_target %}" onsubmit="post.disabled = true; return true;">
    {% csrf_token %}
    <fieldset>
        <input type="hidden" name="next" value="{% url 'comments-xtd-sent' %}" />

        <div class="alert alert-danger" data-comment-element="errors" hidden>
        </div>

        {% for field in form %}
        {% if field.is_hidden %}<div>{{ field }}</div>{% endif %}
        {% endfor %}

        <div style="display:none">{{ form.honeypot }}</div>

        <div class="row form-group {% if 'comment' in form.errors %}has-danger{% endif %}">
            <div class="offset-md-1 col-md-10">
                {{ form.comment }}
            </div>
        </div>

        {% if not request.user.is_authenticated or not request.user.get_full_name %}
        <div class="row form-group {% if 'name' in form.errors %}has-danger{% endif %}">
            <label for="id_name" class="col-form-label col-md-3 text-right">
                {{ form.name.label }}
            </label>
            <div class="col-md-7">
                {{ form.name }}
            </div>
        </div>
        {% endif %}

        {% if not request.user.is_authenticated or not request.user.email %}
        <div class="row form-group {% if 'email' in form.errors %}has-danger{% endif %}">
            <label for="id_email" class="col-form-label col-md-3 text-right">
                {{ form.email.label }}
            </label>
            <div class="col-md-7">
                {{ form.email }}
                <span class="form-text small">{{ form.email.help_text }}</span>
            </div>
        </div>
        {% endif %}

        {% if not request.user.is_authenticated %}
        <div class="row form-group {% if 'url' in form.errors %}has-error{% endif %}">
            <label for="id_url" class="col-form-label col-md-3 text-right">
                {{ form.url.label }}
            </label>
            <div class="col-md-7">
                {{ form.url }}
            </div>
        </div>
        {% endif %}

        <div class="row form-group">
            <div class="offset-md-3 col-md-7">
                <div class="custom-control custom-checkbox">
                    {{ form.followup }}
                    <label for="id_followup{% if cid %}_{{ cid }}{% endif %}" class="custom-control-label">&nbsp;{{ form.followup.label }}</label>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="row form-group">
        <div class="offset-md-3 col-md-7">
            <input type="submit" name="post" value="{% trans 'send' %}" class="btn btn-primary" />
            <input type="submit" name="preview" value="{% trans 'preview' %}" class="btn btn-secondary" />
        </div>
    </div>
</form>

tutorial/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1 class="pb-3 text-center">tutorial</h1>

<div class="row justify-content-center flex-fill">
  <div class="col-md-10">
    <p class="lead">Contains a simple <code>blog</code> application with a <code>Post</code> model with added comments by using <strong>django-contrib-comments</strong> and <strong>django-comments-xtd</strong>.</p>
    <p class="my-3 text-center">Continue to the <a href="{% url 'blog:post_list' %}">blog</a>.</p>
  </div>
</div>
{% endblock %}